x-operator: &operator
  image: humannetwork/operator:test
  env_file: .env

x-othentic-cli: &othentic-cli
  <<: *operator
  env_file: .env
  entrypoint: othentic-cli

x-verifier: &verifier
  image: humannetwork/operator:test
  env_file: .env
  command: [ "./verifier" ]
  environment:
    - REDIS_URL=redis://172.28.0.5:6379/0

# Define a custom network with a subnet
networks:
  human_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16 # Define a subnet for the network

services:
  redis:
    image: redis:latest
    container_name: redis_server
    volumes:
      - ./redis_data:/data # Persist Redis data
    ports:
      - 6379:6379
    networks:
      human_network:
        ipv4_address: 172.28.0.5 # Static IP for Redis
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "20m" # file size

  relay:
    <<: *operator
    container_name: relay
    command: >
      sh -c "sleep 2; \
       ./human_node --bootstrap-peer-id ${BOOTSTRAP_PEER_ID} --bootstrap-multiaddr ${BOOTSTRAP_MULTIADDR} --relay-peer-id ${RELAY_PEER_ID} --relay-multiaddr ${RELAY_MULTIADDR} --port ${TCP_PORT} --redis redis://172.28.0.5:6379/0 | bunyan"
    ports:
      - "${TCP_PORT}:${TCP_PORT}" # TCP
      - "${UDP_PORT}:${UDP_PORT}/udp" # UDP
    environment:
      - BOOTSTRAP_PEER_ID=${BOOTSTRAP_PEER_ID}
      - BOOTSTRAP_MULTIADDR=${BOOTSTRAP_MULTIADDR}
      - RELAY_PEER_ID=${RELAY_PEER_ID}
      - RELAY_MULTIADDR=${RELAY_MULTIADDR}
      - RSA_SEED=${RSA_SEED}
      - SECP256K1_SEED=${SECP256K1_SEED}
      - NODE_TYPE=${NODE_TYPE}
      - NODE_MULTIADDR=${NODE_MULTIADDR}
      - RELAYER_SIGNING_KEY=${RELAYER_SIGNING_KEY}
      - TCP_PORT=${TCP_PORT}
      - UDP_PORT=${UDP_PORT}
    volumes:
      - ./node_state:/state
    networks:
      human_network:
        ipv4_address: 172.28.0.10 # Static IP for relay
    depends_on:
      - redis # Ensure Redis starts first
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "20m" # file size
  avswebapi:
    <<: *verifier
    container_name: avs_web_api
    environment:
      - IPFS_HOST=${IPFS_HOST}
      - REDIS_URL=redis://172.28.0.5:6379/0
      - L1_RPC=${L1_RPC}
    ports:
      - "${AVS_WEBAPI_PORT}:${AVS_WEBAPI_PORT}"
    networks:
      human_network:
        ipv4_address: 172.28.0.20 # Static IP for avs_web_api
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "20m" # file size

  attestor:
    <<: *othentic-cli
    container_name: attestor
    command:
      - "node"
      - "attester"
      # multiaddress of the aggregator node
      - "/ip4/34.229.78.54/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}"
      - "--json-rpc"
      - "--json-rpc.custom-message-enabled"
      - "--avs-webapi"
      - "http://172.28.0.20" # Static IP of avswebapi
      - "--avs-webapi-port"
      - "${AVS_WEBAPI_PORT}"
      - "--l1-chain"
      - "holesky"
      - "--l2-chain"
      - "amoy"
      - "--metrics"
      - "--p2p.datadir"
      - "data/peerstore/attester"
      - "--p2p.port"
      - "9876"
      - "--announced-addresses"
      # Replace with the actual ip and the peer id of the attestor (check note for this)
      - "/ip4/52.15.156.204/tcp/9876/p2p/12D3KooWLUQqXiuLpraZyZAbtNXDEY9DBXZDie7zvfyYnxo3nEY6"
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_ATTESTER}
      - OTHENTIC_BOOTSTRAP_ID=${OTHENTIC_BOOTSTRAP_ID}
      - AVS_WEBAPI_PORT=${AVS_WEBAPI_PORT}
      - LOG_DIR=data/logs/attester
    ports:
      - 9876:9876
      - 8545:8545
    volumes:
      - ./data/peerstore/attestor:/app/data/peerstore/attestor
      - ./data/logs/attestor:/app/logs/peerstore/attestor
    networks:
      human_network:
        ipv4_address: 172.28.0.30 # Static IP for attestor
    depends_on:
      - avswebapi
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "20m"
